apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260624-190216-lnwfd0tlouu1-service
spec:
  selector:
    app: enterprise-system-20260624-190216-lnwfd0tlouu1
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
